/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessControl from "./access-control";
export type { accessControl };
export type { Box } from "./Box";
